### ISSUE TITLE
Get Web Host

### ISSUE THREAD

**Issue by kim00053** [smcs/online-language-lab#4]
Get us a host please, Mr. Battis.

**Comment by battis** [comment]
Checking with @sapoman88 about whether or not he is still using roswell.stmarksschool.org. If not, I will set that up as your basic Apache server. You will have the whole LAMP stack at your disposal (and we can set up other things as well… Ruby, Node.js, whatevs.).

You and @jasonqian, @SoohyoungKim and @com9712 will probably share space until it's clear where your server and their server need to _really_ be. I'm going to put you in the Amazon cloud so that it will be easy to move/expand your server capabilities.

You'll get an SSH key and we'll talk through how to connect to the server through and SSH tunnel (and working through the Linux command line).

Stay tuned. I should have something for you by the end of the day, I hope.

**Comment by battis** [comment]
Okay, @sapoman88 is releasing [Roswell](http://roswell.stmarksschool.org). I will get it refreshed and set up in the next little while.

**Comment by battis** [comment]
Just sent you both credentials for Roswell. We can talk tomorrow about what exactly they mean and how they work. But the short version is: you now have a a database server and a web server that supports PHP. We can set up other CGI scripting languages if needed.
